import { db } from '../src/lib/db'

async function main() {
  console.log('🌱 Seeding database...')

  // ─── 1. Clear existing data ───────────────────────────────────────────────
  console.log('🗑️  Clearing existing data...')
  await db.wishlist.deleteMany()
  await db.orderItem.deleteMany()
  await db.order.deleteMany()
  await db.product.deleteMany()
  await db.user.deleteMany()
  await db.carModel.deleteMany()
  await db.category.deleteMany()
  console.log('✅ Existing data cleared.')

  // ─── 2. Create Categories ─────────────────────────────────────────────────
  console.log('📁 Creating categories...')
  const categories = await Promise.all([
    db.category.create({
      data: {
        name: 'Engine Parts',
        slug: 'engine-parts',
        icon: 'Wrench',
        description: 'Engine components including oil, spark plugs, filters, belts, and gaskets for all major Pakistani car brands.',
      },
    }),
    db.category.create({
      data: {
        name: 'Body Parts',
        slug: 'body-parts',
        icon: 'Car',
        description: 'Exterior body parts including bumpers, fenders, doors, hoods, and side mirrors for all vehicle models.',
      },
    }),
    db.category.create({
      data: {
        name: 'Interior Parts',
        slug: 'interior-parts',
        icon: 'Armchair',
        description: 'Interior components including seats, dashboard, steering wheels, and floor mats to keep your cabin comfortable.',
      },
    }),
    db.category.create({
      data: {
        name: 'Electrical Parts',
        slug: 'electrical-parts',
        icon: 'Zap',
        description: 'Electrical system components including batteries, alternators, starters, lights, and sensors.',
      },
    }),
    db.category.create({
      data: {
        name: 'Suspension Parts',
        slug: 'suspension-parts',
        icon: 'ArrowDownUp',
        description: 'Suspension system parts including shock absorbers, springs, control arms, and bushings for a smooth ride.',
      },
    }),
    db.category.create({
      data: {
        name: 'Brake Parts',
        slug: 'brake-parts',
        icon: 'Disc',
        description: 'Braking system components including brake pads, rotors, calipers, and brake lines for safety.',
      },
    }),
    db.category.create({
      data: {
        name: 'Transmission Parts',
        slug: 'transmission-parts',
        icon: 'Cog',
        description: 'Transmission and drivetrain parts including clutch kits, gearboxes, axles, and CV joints.',
      },
    }),
    db.category.create({
      data: {
        name: 'AC & Cooling',
        slug: 'ac-cooling',
        icon: 'Thermometer',
        description: 'Air conditioning and cooling system parts including compressors, condensers, radiators, and thermostats.',
      },
    }),
  ])
  console.log(`✅ Created ${categories.length} categories.`)

  const [engineParts, bodyParts, interiorParts, electricalParts, suspensionParts, brakeParts, transmissionParts, acCooling] = categories

  // ─── 3. Create Car Models ─────────────────────────────────────────────────
  console.log('🚗 Creating car models...')
  const carModels = await Promise.all([
    db.carModel.create({
      data: { name: 'WagonR', make: 'Suzuki', slug: 'suzuki-wagonr', image: '/cars/suzuki-wagonr.jpg' },
    }),
    db.carModel.create({
      data: { name: 'Alto', make: 'Suzuki', slug: 'suzuki-alto', image: '/cars/suzuki-alto.jpg' },
    }),
    db.carModel.create({
      data: { name: 'Mehran', make: 'Suzuki', slug: 'suzuki-mehran', image: '/cars/suzuki-mehran.jpg' },
    }),
    db.carModel.create({
      data: { name: 'Cultus', make: 'Suzuki', slug: 'suzuki-cultus', image: '/cars/suzuki-cultus.jpg' },
    }),
    db.carModel.create({
      data: { name: 'Corolla XLI', make: 'Toyota', slug: 'toyota-corolla-xli', image: '/cars/toyota-corolla-xli.jpg' },
    }),
    db.carModel.create({
      data: { name: 'Corolla GLI', make: 'Toyota', slug: 'toyota-corolla-gli', image: '/cars/toyota-corolla-gli.jpg' },
    }),
    db.carModel.create({
      data: { name: 'City', make: 'Honda', slug: 'honda-city', image: '/cars/honda-city.jpg' },
    }),
    db.carModel.create({
      data: { name: 'Civic', make: 'Honda', slug: 'honda-civic', image: '/cars/honda-civic.jpg' },
    }),
    db.carModel.create({
      data: { name: 'Coure', make: 'Daihatsu', slug: 'daihatsu-coure', image: '/cars/daihatsu-coure.jpg' },
    }),
    db.carModel.create({
      data: { name: 'Tucson', make: 'Hyundai', slug: 'hyundai-tucson', image: '/cars/hyundai-tucson.jpg' },
    }),
    db.carModel.create({
      data: { name: 'HS', make: 'MG', slug: 'mg-hs', image: '/cars/mg-hs.jpg' },
    }),
    db.carModel.create({
      data: { name: 'ZS', make: 'MG', slug: 'mg-zs', image: '/cars/mg-zs.jpg' },
    }),
  ])
  console.log(`✅ Created ${carModels.length} car models.`)

  const [wagonR, alto, mehran, cultus, corollaXli, corollaGli, city, civic, coure, tucson, mgHs, mgZs] = carModels

  // ─── 4. Create Products ───────────────────────────────────────────────────
  console.log('📦 Creating products...')

  const productsData = [
    // ── Engine Parts ──────────────────────────────────────────────────────
    {
      name: 'Shell Helix HX5 10W-40 Engine Oil 4L',
      slug: 'shell-helix-hx5-10w40-engine-oil-4l',
      description: 'Premium quality engine oil suitable for Suzuki and Toyota vehicles. Provides excellent engine protection and cleaning performance. API SN certified for modern engines.',
      price: 4800,
      condition: 'new',
      stock: 45,
      images: '/products/engine-1.jpg',
      sku: 'RG-OIL-001',
      partNumber: 'SH-HX5-10W40-4L',
      categoryId: engineParts.id,
      carModelId: corollaXli.id,
      featured: true,
    },
    {
      name: 'NGK BKR5E Spark Plugs (Set of 4)',
      slug: 'ngk-bkr5e-spark-plugs-set-4',
      description: 'Original NGK spark plugs for Suzuki Alto and WagonR. Ensures smooth ignition and better fuel economy. Nickel alloy center electrode for long life.',
      price: 2200,
      condition: 'new',
      stock: 60,
      images: '/products/engine-2.jpg',
      sku: 'RG-SPK-002',
      partNumber: 'NGK-BKR5E',
      categoryId: engineParts.id,
      carModelId: alto.id,
      featured: false,
    },
    {
      name: 'Suzuki Mehran Air Filter Element',
      slug: 'suzuki-mehran-air-filter-element',
      description: 'High-quality air filter for Suzuki Mehran. Filters dust and debris to protect your engine. Easy drop-in replacement, no modifications needed.',
      price: 650,
      condition: 'new',
      stock: 80,
      images: '/products/engine-3.jpg',
      sku: 'RG-AFL-003',
      partNumber: 'SZ-MRN-AF01',
      categoryId: engineParts.id,
      carModelId: mehran.id,
      featured: false,
    },
    {
      name: 'Toyota Corolla Timing Belt Kit',
      slug: 'toyota-corolla-timing-belt-kit',
      description: 'Complete timing belt kit for Toyota Corolla XLI/GLI 1.3L. Includes timing belt, tensioner pulley, and idler pulley. Genuine quality for reliable performance.',
      price: 8500,
      condition: 'new',
      stock: 20,
      images: '/products/engine-4.jpg',
      sku: 'RG-TBK-004',
      partNumber: 'TY-CRL-TBKIT',
      categoryId: engineParts.id,
      carModelId: corollaXli.id,
      featured: true,
    },
    {
      name: 'Honda City Cylinder Head Gasket',
      slug: 'honda-city-cylinder-head-gasket',
      description: 'OEM replacement cylinder head gasket for Honda City 1.5L. Made from high-quality multi-layer steel for superior sealing. Resists blowouts under high compression.',
      price: 4500,
      condition: 'new',
      stock: 15,
      images: '/products/engine-5.jpg',
      sku: 'RG-GSK-005',
      partNumber: 'HN-CTY-HG01',
      categoryId: engineParts.id,
      carModelId: city.id,
      featured: false,
    },
    {
      name: 'Suzuki WagonR Oil Filter',
      slug: 'suzuki-wagonr-oil-filter',
      description: 'Replacement oil filter for Suzuki WagonR K10B engine. High filtration efficiency to keep engine oil clean. Compatible with all WagonR model years.',
      price: 500,
      condition: 'new',
      stock: 100,
      images: '/products/engine-6.jpg',
      sku: 'RG-OFL-006',
      partNumber: 'SZ-WGR-OF01',
      categoryId: engineParts.id,
      carModelId: wagonR.id,
      featured: false,
    },
    {
      name: 'Honda Civic Alternator Belt (Used)',
      slug: 'honda-civic-alternator-belt-used',
      description: 'Used alternator/AC belt for Honda Civic 1.8L. Good condition with plenty of life remaining. Removed from low-mileage vehicle.',
      price: 1200,
      condition: 'used',
      stock: 8,
      images: '/products/engine-7.jpg',
      sku: 'RG-BLT-007',
      partNumber: 'HN-CVC-ABELT',
      categoryId: engineParts.id,
      carModelId: civic.id,
      featured: false,
    },
    {
      name: 'Suzuki Cultus Engine Mount (Used)',
      slug: 'suzuki-cultus-engine-mount-used',
      description: 'Used engine mount for Suzuki Cultus. Properly inspected and in good working condition. Reduces engine vibration effectively.',
      price: 1800,
      condition: 'used',
      stock: 5,
      images: '/products/engine-8.jpg',
      sku: 'RG-EMT-008',
      partNumber: 'SZ-CLS-EM01',
      categoryId: engineParts.id,
      carModelId: cultus.id,
      featured: false,
    },

    // ── Body Parts ────────────────────────────────────────────────────────
    {
      name: 'Toyota Corolla Front Bumper',
      slug: 'toyota-corolla-front-bumper',
      description: 'Brand new front bumper for Toyota Corolla XLI 2014-2021. Unpainted, ready for primer and color matching. High-impact ABS plastic construction.',
      price: 12000,
      condition: 'new',
      stock: 10,
      images: '/products/body-1.jpg',
      sku: 'RG-BMP-009',
      partNumber: 'TY-CRL-FB01',
      categoryId: bodyParts.id,
      carModelId: corollaXli.id,
      featured: true,
    },
    {
      name: 'Suzuki Alto Left Side Mirror',
      slug: 'suzuki-alto-left-side-mirror',
      description: 'Left side mirror assembly for Suzuki Alto. Manual adjustment type. Complete with mounting bracket and wiring connector.',
      price: 2500,
      condition: 'new',
      stock: 25,
      images: '/products/body-2.jpg',
      sku: 'RG-MIR-010',
      partNumber: 'SZ-ALT-LM01',
      categoryId: bodyParts.id,
      carModelId: alto.id,
      featured: false,
    },
    {
      name: 'Honda City Front Fender (Left)',
      slug: 'honda-city-front-fender-left',
      description: 'Front left fender for Honda City 2014-2020. Metal construction, primed and ready for paint. Direct bolt-on replacement.',
      price: 7500,
      condition: 'new',
      stock: 8,
      images: '/products/body-3.jpg',
      sku: 'RG-FND-011',
      partNumber: 'HN-CTY-LF01',
      categoryId: bodyParts.id,
      carModelId: city.id,
      featured: false,
    },
    {
      name: 'Suzuki Mehran Front Bumper (Used)',
      slug: 'suzuki-mehran-front-bumper-used',
      description: 'Used front bumper for Suzuki Mehran in good condition. Minor scratches but no cracks or damage. White color, can be repainted.',
      price: 3500,
      condition: 'used',
      stock: 6,
      images: '/products/body-4.jpg',
      sku: 'RG-BMP-012',
      partNumber: 'SZ-MRN-FB01',
      categoryId: bodyParts.id,
      carModelId: mehran.id,
      featured: false,
    },
    {
      name: 'Honda Civic Rear Bumper (Used)',
      slug: 'honda-civic-rear-bumper-used',
      description: 'Used rear bumper for Honda Civic 2016-2021. Good overall condition with minor scuffs. Perfect for replacing a damaged bumper on a budget.',
      price: 8000,
      condition: 'used',
      stock: 4,
      images: '/products/body-5.jpg',
      sku: 'RG-BMP-013',
      partNumber: 'HN-CVC-RB01',
      categoryId: bodyParts.id,
      carModelId: civic.id,
      featured: false,
    },
    {
      name: 'MG HS Right Side Mirror',
      slug: 'mg-hs-right-side-mirror',
      description: 'Right side power mirror for MG HS. Electric adjustment with integrated turn signal. OEM-style replacement for perfect fit.',
      price: 6500,
      condition: 'new',
      stock: 12,
      images: '/products/body-6.jpg',
      sku: 'RG-MIR-014',
      partNumber: 'MG-HS-RM01',
      categoryId: bodyParts.id,
      carModelId: mgHs.id,
      featured: false,
    },
    {
      name: 'Suzuki WagonR Bonnet/Hood (Used)',
      slug: 'suzuki-wagonr-bonnet-hood-used',
      description: 'Used bonnet/hood for Suzuki WagonR. Good structural condition, no major dents. Requires painting to match your vehicle color.',
      price: 5500,
      condition: 'used',
      stock: 3,
      images: '/products/body-7.jpg',
      sku: 'RG-HOD-015',
      partNumber: 'SZ-WGR-HD01',
      categoryId: bodyParts.id,
      carModelId: wagonR.id,
      featured: false,
    },
    {
      name: 'Toyota Corolla GLI Front Door (Left, Used)',
      slug: 'toyota-corolla-gli-front-door-left-used',
      description: 'Used front left door shell for Toyota Corolla GLI. Complete with window regulator and door lock mechanism. Good working condition.',
      price: 18000,
      condition: 'used',
      stock: 2,
      images: '/products/body-8.jpg',
      sku: 'RG-DOR-016',
      partNumber: 'TY-CGL-LD01',
      categoryId: bodyParts.id,
      carModelId: corollaGli.id,
      featured: false,
    },

    // ── Interior Parts ────────────────────────────────────────────────────
    {
      name: 'Honda City Floor Mats (Full Set)',
      slug: 'honda-city-floor-mats-full-set',
      description: 'Complete set of 5 floor mats for Honda City. Heavy-duty rubber with anti-slip backing. Custom-fit design for perfect coverage. Easy to clean and maintain.',
      price: 3500,
      condition: 'new',
      stock: 30,
      images: '/products/interior-1.jpg',
      sku: 'RG-INT-017',
      partNumber: 'HN-CTY-FM01',
      categoryId: interiorParts.id,
      carModelId: city.id,
      featured: true,
    },
    {
      name: 'Toyota Corolla Steering Wheel',
      slug: 'toyota-corolla-steering-wheel',
      description: 'Replacement steering wheel for Toyota Corolla XLI/GLI. Leather-wrapped grip for comfortable driving. Includes horn button and airbag cover.',
      price: 9500,
      condition: 'new',
      stock: 10,
      images: '/products/interior-2.jpg',
      sku: 'RG-INT-018',
      partNumber: 'TY-CRL-SW01',
      categoryId: interiorParts.id,
      carModelId: corollaXli.id,
      featured: false,
    },
    {
      name: 'Suzuki Alto Dashboard Cover',
      slug: 'suzuki-alto-dashboard-cover',
      description: 'Dashboard cover/mat for Suzuki Alto. Protects from sun damage and reduces glare. Non-slip backing keeps items in place.',
      price: 1500,
      condition: 'new',
      stock: 20,
      images: '/products/interior-3.jpg',
      sku: 'RG-INT-019',
      partNumber: 'SZ-ALT-DC01',
      categoryId: interiorParts.id,
      carModelId: alto.id,
      featured: false,
    },
    {
      name: 'Suzuki Cultus Front Seat Cover Set',
      slug: 'suzuki-cultus-front-seat-cover-set',
      description: 'Front seat covers for Suzuki Cultus. Made from breathable fabric material. Easy installation with elastic straps. Protects original seats from wear.',
      price: 2800,
      condition: 'new',
      stock: 18,
      images: '/products/interior-4.jpg',
      sku: 'RG-INT-020',
      partNumber: 'SZ-CLS-SC01',
      categoryId: interiorParts.id,
      carModelId: cultus.id,
      featured: false,
    },
    {
      name: 'Honda Civic Dashboard Assembly (Used)',
      slug: 'honda-civic-dashboard-assembly-used',
      description: 'Used complete dashboard assembly for Honda Civic. Includes instrument cluster surround and glove box. Good condition with no cracks.',
      price: 25000,
      condition: 'used',
      stock: 2,
      images: '/products/interior-5.jpg',
      sku: 'RG-INT-021',
      partNumber: 'HN-CVC-DB01',
      categoryId: interiorParts.id,
      carModelId: civic.id,
      featured: false,
    },
    {
      name: 'Daihatsu Coure Floor Mats (Used)',
      slug: 'daihatsu-coure-floor-mats-used',
      description: 'Used floor mats for Daihatsu Coure. Rubber construction, decent condition with some wear. Budget-friendly option for interior protection.',
      price: 800,
      condition: 'used',
      stock: 5,
      images: '/products/interior-6.jpg',
      sku: 'RG-INT-022',
      partNumber: 'DH-CRE-FM01',
      categoryId: interiorParts.id,
      carModelId: coure.id,
      featured: false,
    },
    {
      name: 'Suzuki Mehran Steering Wheel (Used)',
      slug: 'suzuki-mehran-steering-wheel-used',
      description: 'Used steering wheel for Suzuki Mehran. Good grip condition, horn button functional. Straight swap replacement.',
      price: 1500,
      condition: 'used',
      stock: 4,
      images: '/products/interior-7.jpg',
      sku: 'RG-INT-023',
      partNumber: 'SZ-MRN-SW01',
      categoryId: interiorParts.id,
      carModelId: mehran.id,
      featured: false,
    },

    // ── Electrical Parts ──────────────────────────────────────────────────
    {
      name: 'Osram 12V 60/55W Headlight Bulbs (Pair)',
      slug: 'osram-12v-headlight-bulbs-pair',
      description: 'Original Osram H4 headlight bulbs for all Pakistani vehicles. 60/55W dual filament for high and low beam. Bright white light for safer night driving.',
      price: 1800,
      condition: 'new',
      stock: 50,
      images: '/products/electrical-1.jpg',
      sku: 'RG-ELC-024',
      partNumber: 'OS-H4-6055',
      categoryId: electricalParts.id,
      carModelId: corollaGli.id,
      featured: true,
    },
    {
      name: 'AGS Battery 50Ah for Suzuki',
      slug: 'ags-battery-50ah-suzuki',
      description: 'AGS 50Ah maintenance-free battery for Suzuki Alto, Mehran, and WagonR. Reliable starting power in all weather conditions. 1-year warranty included.',
      price: 9500,
      condition: 'new',
      stock: 15,
      images: '/products/electrical-2.jpg',
      sku: 'RG-ELC-025',
      partNumber: 'AGS-50MF',
      categoryId: electricalParts.id,
      carModelId: alto.id,
      featured: true,
    },
    {
      name: 'Toyota Corolla Alternator (Used)',
      slug: 'toyota-corolla-alternator-used',
      description: 'Used alternator for Toyota Corolla 1.3L. Output: 80A. Tested and in good working condition. Direct fit, plug-and-play installation.',
      price: 12000,
      condition: 'used',
      stock: 5,
      images: '/products/electrical-3.jpg',
      sku: 'RG-ELC-026',
      partNumber: 'TY-CRL-ALT01',
      categoryId: electricalParts.id,
      carModelId: corollaXli.id,
      featured: false,
    },
    {
      name: 'Honda City Starter Motor (Used)',
      slug: 'honda-city-starter-motor-used',
      description: 'Used starter motor for Honda City 1.5L. Tested before removal, spins freely and engages properly. Good replacement for faulty starters.',
      price: 8500,
      condition: 'used',
      stock: 4,
      images: '/products/electrical-4.jpg',
      sku: 'RG-ELC-027',
      partNumber: 'HN-CTY-STR01',
      categoryId: electricalParts.id,
      carModelId: city.id,
      featured: false,
    },
    {
      name: 'Suzuki WagonR Oxygen Sensor (Used)',
      slug: 'suzuki-wagonr-oxygen-sensor-used',
      description: 'Used O2 sensor for Suzuki WagonR K10B engine. Helps maintain proper air-fuel ratio. Good working condition, removed from running vehicle.',
      price: 3500,
      condition: 'used',
      stock: 6,
      images: '/products/electrical-5.jpg',
      sku: 'RG-ELC-028',
      partNumber: 'SZ-WGR-O2S01',
      categoryId: electricalParts.id,
      carModelId: wagonR.id,
      featured: false,
    },
    {
      name: 'MG HS LED Tail Light (Right)',
      slug: 'mg-hs-led-tail-light-right',
      description: 'Brand new LED tail light assembly for MG HS right side. Modern LED technology for brighter illumination and longer life. OEM-quality replacement.',
      price: 15000,
      condition: 'new',
      stock: 8,
      images: '/products/electrical-6.jpg',
      sku: 'RG-ELC-029',
      partNumber: 'MG-HS-RTL01',
      categoryId: electricalParts.id,
      carModelId: mgHs.id,
      featured: false,
    },
    {
      name: 'Hyundai Tucson MAP Sensor',
      slug: 'hyundai-tucson-map-sensor',
      description: 'Manifold absolute pressure sensor for Hyundai Tucson. Essential for proper engine management and fuel efficiency. Brand new OEM-equivalent part.',
      price: 6800,
      condition: 'new',
      stock: 10,
      images: '/products/electrical-7.jpg',
      sku: 'RG-ELC-030',
      partNumber: 'HY-TCS-MAP01',
      categoryId: electricalParts.id,
      carModelId: tucson.id,
      featured: false,
    },
    {
      name: 'Suzuki Mehran Horn Set',
      slug: 'suzuki-mehran-horn-set',
      description: 'Replacement horn set for Suzuki Mehran. High and low tone pair for proper horn sound. Easy two-wire installation.',
      price: 1200,
      condition: 'new',
      stock: 25,
      images: '/products/electrical-8.jpg',
      sku: 'RG-ELC-031',
      partNumber: 'SZ-MRN-HRN01',
      categoryId: electricalParts.id,
      carModelId: mehran.id,
      featured: false,
    },

    // ── Suspension Parts ──────────────────────────────────────────────────
    {
      name: 'Toyota Corolla Front Shock Absorbers (Pair)',
      slug: 'toyota-corolla-front-shock-absorbers-pair',
      description: 'Brand new front shock absorbers for Toyota Corolla XLI/GLI. Gas-charged for superior damping performance. Restores ride quality and handling.',
      price: 14000,
      condition: 'new',
      stock: 12,
      images: '/products/suspension-1.jpg',
      sku: 'RG-SUS-032',
      partNumber: 'TY-CRL-FSA01',
      categoryId: suspensionParts.id,
      carModelId: corollaXli.id,
      featured: true,
    },
    {
      name: 'Suzuki Alto Rear Shock Absorbers (Pair, Used)',
      slug: 'suzuki-alto-rear-shock-absorbers-pair-used',
      description: 'Used rear shock absorbers for Suzuki Alto. Still in decent working condition with no leaks. Budget-friendly option for suspension repair.',
      price: 3500,
      condition: 'used',
      stock: 6,
      images: '/products/suspension-2.jpg',
      sku: 'RG-SUS-033',
      partNumber: 'SZ-ALT-RSA01',
      categoryId: suspensionParts.id,
      carModelId: alto.id,
      featured: false,
    },
    {
      name: 'Honda Civic Front Coil Springs (Pair)',
      slug: 'honda-civic-front-coil-springs-pair',
      description: 'Front coil springs for Honda Civic 2016-2021. Heavy-duty construction for long-lasting performance. Restores proper ride height.',
      price: 7500,
      condition: 'new',
      stock: 10,
      images: '/products/suspension-3.jpg',
      sku: 'RG-SUS-034',
      partNumber: 'HN-CVC-FCS01',
      categoryId: suspensionParts.id,
      carModelId: civic.id,
      featured: false,
    },
    {
      name: 'Suzuki WagonR Lower Control Arm (Left, Used)',
      slug: 'suzuki-wagonr-lower-control-arm-left-used',
      description: 'Used lower control arm for Suzuki WagonR left side. Ball joint and bushings intact. Inspected for cracks and wear.',
      price: 4000,
      condition: 'used',
      stock: 4,
      images: '/products/suspension-4.jpg',
      sku: 'RG-SUS-035',
      partNumber: 'SZ-WGR-LCA01',
      categoryId: suspensionParts.id,
      carModelId: wagonR.id,
      featured: false,
    },
    {
      name: 'Daihatsu Coure Suspension Bushings Kit',
      slug: 'daihatsu-coure-suspension-bushings-kit',
      description: 'Complete suspension bushing kit for Daihatsu Coure. Includes all major bushings for front and rear suspension. Polyurethane material for longer life.',
      price: 3200,
      condition: 'new',
      stock: 15,
      images: '/products/suspension-5.jpg',
      sku: 'RG-SUS-036',
      partNumber: 'DH-CRE-SBK01',
      categoryId: suspensionParts.id,
      carModelId: coure.id,
      featured: false,
    },
    {
      name: 'MG ZS Rear Shock Absorbers (Pair)',
      slug: 'mg-zs-rear-shock-absorbers-pair',
      description: 'New rear shock absorbers for MG ZS. Gas-charged for improved stability and comfort. OEM-specification replacement part.',
      price: 16000,
      condition: 'new',
      stock: 8,
      images: '/products/suspension-6.jpg',
      sku: 'RG-SUS-037',
      partNumber: 'MG-ZS-RSA01',
      categoryId: suspensionParts.id,
      carModelId: mgZs.id,
      featured: false,
    },
    {
      name: 'Hyundai Tucson Front Control Arm (Right, Used)',
      slug: 'hyundai-tucson-front-control-arm-right-used',
      description: 'Used right front control arm for Hyundai Tucson. Ball joint in good condition. Cost-effective replacement for damaged control arm.',
      price: 9500,
      condition: 'used',
      stock: 3,
      images: '/products/suspension-7.jpg',
      sku: 'RG-SUS-038',
      partNumber: 'HY-TCS-RCA01',
      categoryId: suspensionParts.id,
      carModelId: tucson.id,
      featured: false,
    },

    // ── Brake Parts ───────────────────────────────────────────────────────
    {
      name: 'Toyota Corolla Front Brake Pads',
      slug: 'toyota-corolla-front-brake-pads',
      description: 'Premium ceramic front brake pads for Toyota Corolla XLI/GLI. Low dust formulation with quiet operation. Excellent stopping power in all conditions.',
      price: 4500,
      condition: 'new',
      stock: 25,
      images: '/products/brake-1.jpg',
      sku: 'RG-BRK-039',
      partNumber: 'TY-CRL-FBP01',
      categoryId: brakeParts.id,
      carModelId: corollaXli.id,
      featured: true,
    },
    {
      name: 'Honda City Front Brake Rotors (Pair)',
      slug: 'honda-city-front-brake-rotors-pair',
      description: 'Front brake disc rotors for Honda City. Vented design for better heat dissipation. Precision-machined for smooth braking performance.',
      price: 8000,
      condition: 'new',
      stock: 10,
      images: '/products/brake-2.jpg',
      sku: 'RG-BRK-040',
      partNumber: 'HN-CTY-FDR01',
      categoryId: brakeParts.id,
      carModelId: city.id,
      featured: false,
    },
    {
      name: 'Suzuki Alto Brake Caliper (Front Left, Used)',
      slug: 'suzuki-alto-brake-caliper-front-left-used',
      description: 'Used front left brake caliper for Suzuki Alto. Piston moves freely, no leaks. Good budget replacement option.',
      price: 2800,
      condition: 'used',
      stock: 5,
      images: '/products/brake-3.jpg',
      sku: 'RG-BRK-041',
      partNumber: 'SZ-ALT-FLC01',
      categoryId: brakeParts.id,
      carModelId: alto.id,
      featured: false,
    },
    {
      name: 'Suzuki Mehran Rear Brake Shoes',
      slug: 'suzuki-mehran-rear-brake-shoes',
      description: 'Rear brake shoes for Suzuki Mehran. High-quality friction material for reliable braking. Direct replacement, no modifications needed.',
      price: 1200,
      condition: 'new',
      stock: 35,
      images: '/products/brake-4.jpg',
      sku: 'RG-BRK-042',
      partNumber: 'SZ-MRN-RBS01',
      categoryId: brakeParts.id,
      carModelId: mehran.id,
      featured: false,
    },
    {
      name: 'Honda Civic Brake Lines Kit',
      slug: 'honda-civic-brake-lines-kit',
      description: 'Complete brake line kit for Honda Civic. Pre-bent steel lines with correct fittings. Essential for brake system restoration.',
      price: 5500,
      condition: 'new',
      stock: 8,
      images: '/products/brake-5.jpg',
      sku: 'RG-BRK-043',
      partNumber: 'HN-CVC-BLK01',
      categoryId: brakeParts.id,
      carModelId: civic.id,
      featured: false,
    },
    {
      name: 'Suzuki Cultus Front Brake Pads (Used)',
      slug: 'suzuki-cultus-front-brake-pads-used',
      description: 'Used front brake pads for Suzuki Cultus with approximately 60% life remaining. Suitable as a temporary replacement.',
      price: 1500,
      condition: 'used',
      stock: 4,
      images: '/products/brake-6.jpg',
      sku: 'RG-BRK-044',
      partNumber: 'SZ-CLS-FBP01',
      categoryId: brakeParts.id,
      carModelId: cultus.id,
      featured: false,
    },
    {
      name: 'MG HS Front Brake Pads',
      slug: 'mg-hs-front-brake-pads',
      description: 'Front brake pads for MG HS. Semi-metallic compound for consistent braking. Low noise and vibration. OEM-equivalent quality.',
      price: 6500,
      condition: 'new',
      stock: 12,
      images: '/products/brake-7.jpg',
      sku: 'RG-BRK-045',
      partNumber: 'MG-HS-FBP01',
      categoryId: brakeParts.id,
      carModelId: mgHs.id,
      featured: false,
    },

    // ── Transmission Parts ────────────────────────────────────────────────
    {
      name: 'Honda City Clutch Kit (Complete)',
      slug: 'honda-city-clutch-kit-complete',
      description: 'Complete clutch kit for Honda City 1.5L. Includes clutch disc, pressure plate, and release bearing. Smooth engagement and long-lasting performance.',
      price: 12000,
      condition: 'new',
      stock: 10,
      images: '/products/transmission-1.jpg',
      sku: 'RG-TRN-046',
      partNumber: 'HN-CTY-CK01',
      categoryId: transmissionParts.id,
      carModelId: city.id,
      featured: true,
    },
    {
      name: 'Suzuki Mehran Clutch Cable',
      slug: 'suzuki-mehran-clutch-cable',
      description: 'Replacement clutch cable for Suzuki Mehran. Stainless steel inner wire with protective outer casing. Direct fit, easy installation.',
      price: 950,
      condition: 'new',
      stock: 20,
      images: '/products/transmission-2.jpg',
      sku: 'RG-TRN-047',
      partNumber: 'SZ-MRN-CC01',
      categoryId: transmissionParts.id,
      carModelId: mehran.id,
      featured: false,
    },
    {
      name: 'Toyota Corolla CV Axle (Right, Used)',
      slug: 'toyota-corolla-cv-axle-right-used',
      description: 'Used right CV axle/driveshaft for Toyota Corolla. Boots intact, no clicking noise. Tested and in good working condition.',
      price: 7000,
      condition: 'used',
      stock: 4,
      images: '/products/transmission-3.jpg',
      sku: 'RG-TRN-048',
      partNumber: 'TY-CRL-RAX01',
      categoryId: transmissionParts.id,
      carModelId: corollaGli.id,
      featured: false,
    },
    {
      name: 'Suzuki Alto Gear Shift Cable',
      slug: 'suzuki-alto-gear-shift-cable',
      description: 'Gear shift cable for Suzuki Alto. Connects shifter to transmission. OEM-quality replacement for smooth gear changes.',
      price: 2200,
      condition: 'new',
      stock: 15,
      images: '/products/transmission-4.jpg',
      sku: 'RG-TRN-049',
      partNumber: 'SZ-ALT-GSC01',
      categoryId: transmissionParts.id,
      carModelId: alto.id,
      featured: false,
    },
    {
      name: 'Honda Civic Clutch Master Cylinder (Used)',
      slug: 'honda-civic-clutch-master-cylinder-used',
      description: 'Used clutch master cylinder for Honda Civic. No leaks, piston operates smoothly. Direct replacement for hydraulic clutch system.',
      price: 4500,
      condition: 'used',
      stock: 3,
      images: '/products/transmission-5.jpg',
      sku: 'RG-TRN-050',
      partNumber: 'HN-CVC-CMC01',
      categoryId: transmissionParts.id,
      carModelId: civic.id,
      featured: false,
    },
    {
      name: 'Suzuki WagonR CV Joint (Left, Used)',
      slug: 'suzuki-wagonr-cv-joint-left-used',
      description: 'Used left CV joint for Suzuki WagonR. Good condition with no play or noise. Boot included. Affordable replacement option.',
      price: 3200,
      condition: 'used',
      stock: 5,
      images: '/products/transmission-6.jpg',
      sku: 'RG-TRN-051',
      partNumber: 'SZ-WGR-LCV01',
      categoryId: transmissionParts.id,
      carModelId: wagonR.id,
      featured: false,
    },
    {
      name: 'Daihatsu Coure Clutch Kit',
      slug: 'daihatsu-coure-clutch-kit',
      description: 'Brand new clutch kit for Daihatsu Coure. Includes clutch plate, pressure plate, and thrust bearing. Reliable performance for daily driving.',
      price: 5500,
      condition: 'new',
      stock: 8,
      images: '/products/transmission-7.jpg',
      sku: 'RG-TRN-052',
      partNumber: 'DH-CRE-CK01',
      categoryId: transmissionParts.id,
      carModelId: coure.id,
      featured: false,
    },
    {
      name: 'Suzuki Cultus Gearbox Mount (Used)',
      slug: 'suzuki-cultus-gearbox-mount-used',
      description: 'Used gearbox/transmission mount for Suzuki Cultus. Rubber still firm with no excessive cracking. Reduces transmission vibration.',
      price: 1800,
      condition: 'used',
      stock: 4,
      images: '/products/transmission-8.jpg',
      sku: 'RG-TRN-053',
      partNumber: 'SZ-CLS-GM01',
      categoryId: transmissionParts.id,
      carModelId: cultus.id,
      featured: false,
    },

    // ── AC & Cooling ──────────────────────────────────────────────────────
    {
      name: 'Toyota Corolla AC Compressor (Used)',
      slug: 'toyota-corolla-ac-compressor-used',
      description: 'Used AC compressor for Toyota Corolla. Tested and blowing cold. Pulley spins freely with no noise. Cost-effective replacement for your AC system.',
      price: 15000,
      condition: 'used',
      stock: 4,
      images: '/products/ac-1.jpg',
      sku: 'RG-ACC-054',
      partNumber: 'TY-CRL-ACP01',
      categoryId: acCooling.id,
      carModelId: corollaXli.id,
      featured: false,
    },
    {
      name: 'Honda City Radiator (New)',
      slug: 'honda-city-radiator-new',
      description: 'Brand new aluminum radiator for Honda City. High-efficiency core design for better cooling. Direct fit with all mounting points and hose connections.',
      price: 11000,
      condition: 'new',
      stock: 8,
      images: '/products/ac-2.jpg',
      sku: 'RG-ACC-055',
      partNumber: 'HN-CTY-RAD01',
      categoryId: acCooling.id,
      carModelId: city.id,
      featured: true,
    },
    {
      name: 'Suzuki Alto AC Condenser',
      slug: 'suzuki-alto-ac-condenser',
      description: 'AC condenser for Suzuki Alto. Aluminum construction for efficient heat exchange. Ensures proper AC cooling performance in hot Pakistani summers.',
      price: 6500,
      condition: 'new',
      stock: 10,
      images: '/products/ac-3.jpg',
      sku: 'RG-ACC-056',
      partNumber: 'SZ-ALT-ACD01',
      categoryId: acCooling.id,
      carModelId: alto.id,
      featured: false,
    },
    {
      name: 'Suzuki Mehran Radiator (Used)',
      slug: 'suzuki-mehran-radiator-used',
      description: 'Used radiator for Suzuki Mehran. No leaks, fins in decent condition. Good budget replacement. Compatible with all Mehran model years.',
      price: 4500,
      condition: 'used',
      stock: 5,
      images: '/products/ac-4.jpg',
      sku: 'RG-ACC-057',
      partNumber: 'SZ-MRN-RAD01',
      categoryId: acCooling.id,
      carModelId: mehran.id,
      featured: false,
    },
    {
      name: 'Honda Civic Cooling Fan Assembly',
      slug: 'honda-civic-cooling-fan-assembly',
      description: 'Complete cooling fan assembly for Honda Civic. Includes fan motor, blades, and shroud. Maintains optimal engine temperature.',
      price: 7500,
      condition: 'new',
      stock: 8,
      images: '/products/ac-5.jpg',
      sku: 'RG-ACC-058',
      partNumber: 'HN-CVC-CFA01',
      categoryId: acCooling.id,
      carModelId: civic.id,
      featured: false,
    },
    {
      name: 'Suzuki WagonR Thermostat',
      slug: 'suzuki-wagonr-thermostat',
      description: 'Replacement thermostat for Suzuki WagonR K10B engine. Opens at 82°C for proper engine warm-up and temperature regulation. Prevents overheating.',
      price: 950,
      condition: 'new',
      stock: 20,
      images: '/products/ac-6.jpg',
      sku: 'RG-ACC-059',
      partNumber: 'SZ-WGR-THM01',
      categoryId: acCooling.id,
      carModelId: wagonR.id,
      featured: false,
    },
    {
      name: 'Hyundai Tucson AC Compressor',
      slug: 'hyundai-tucson-ac-compressor',
      description: 'Brand new AC compressor for Hyundai Tucson. High-quality replacement with proper refrigerant compatibility. Restores full cooling performance.',
      price: 35000,
      condition: 'new',
      stock: 5,
      images: '/products/ac-7.jpg',
      sku: 'RG-ACC-060',
      partNumber: 'HY-TCS-ACP01',
      categoryId: acCooling.id,
      carModelId: tucson.id,
      featured: false,
    },
    {
      name: 'MG HS Radiator Cooling Fan (Used)',
      slug: 'mg-hs-radiator-cooling-fan-used',
      description: 'Used radiator cooling fan for MG HS. Motor and blades in good working condition. Direct fit replacement for cooling system repair.',
      price: 8500,
      condition: 'used',
      stock: 3,
      images: '/products/ac-8.jpg',
      sku: 'RG-ACC-061',
      partNumber: 'MG-HS-CFA01',
      categoryId: acCooling.id,
      carModelId: mgHs.id,
      featured: false,
    },
    {
      name: 'Toyota Corolla GLI AC Expansion Valve',
      slug: 'toyota-corolla-gli-ac-expansion-valve',
      description: 'AC expansion valve for Toyota Corolla GLI. Controls refrigerant flow for optimal AC performance. OEM-quality replacement part.',
      price: 2800,
      condition: 'new',
      stock: 12,
      images: '/products/ac-9.jpg',
      sku: 'RG-ACC-062',
      partNumber: 'TY-CGL-AEV01',
      categoryId: acCooling.id,
      carModelId: corollaGli.id,
      featured: false,
    },
    {
      name: 'Suzuki Cultus Water Pump',
      slug: 'suzuki-cultus-water-pump',
      description: 'New water pump for Suzuki Cultus. Heavy-duty impeller design for efficient coolant circulation. Includes gasket for proper sealing.',
      price: 4200,
      condition: 'new',
      stock: 10,
      images: '/products/ac-10.jpg',
      sku: 'RG-ACC-063',
      partNumber: 'SZ-CLS-WP01',
      categoryId: acCooling.id,
      carModelId: cultus.id,
      featured: false,
    },

    // ── Extra Products to Ensure Rich Data ─────────────────────────────────
    {
      name: 'Suzuki WagonR AC Cabin Filter',
      slug: 'suzuki-wagonr-ac-cabin-filter',
      description: 'Cabin air filter for Suzuki WagonR. Activated carbon layer filters dust, pollen, and odors. Improves AC airflow and cabin air quality.',
      price: 1100,
      condition: 'new',
      stock: 30,
      images: '/products/engine-9.jpg',
      sku: 'RG-CFL-064',
      partNumber: 'SZ-WGR-CF01',
      categoryId: engineParts.id,
      carModelId: wagonR.id,
      featured: false,
    },
    {
      name: 'Daihatsu Coure Alternator (Used)',
      slug: 'daihatsu-coure-alternator-used',
      description: 'Used alternator for Daihatsu Coure. Output: 45A. Tested and charging properly. Good replacement at a fraction of the new price.',
      price: 5000,
      condition: 'used',
      stock: 3,
      images: '/products/electrical-9.jpg',
      sku: 'RG-ELC-065',
      partNumber: 'DH-CRE-ALT01',
      categoryId: electricalParts.id,
      carModelId: coure.id,
      featured: false,
    },
    {
      name: 'MG ZS Brake Rotors (Front Pair)',
      slug: 'mg-zs-brake-rotors-front-pair',
      description: 'Front brake rotors for MG ZS. Vented design for improved cooling. Precision-balanced for vibration-free braking.',
      price: 14000,
      condition: 'new',
      stock: 6,
      images: '/products/brake-8.jpg',
      sku: 'RG-BRK-066',
      partNumber: 'MG-ZS-FDR01',
      categoryId: brakeParts.id,
      carModelId: mgZs.id,
      featured: false,
    },
    {
      name: 'Toyota Corolla Engine Oil 5W-30 Full Synthetic 4L',
      slug: 'toyota-corolla-engine-oil-5w30-full-synthetic-4l',
      description: 'Full synthetic 5W-30 engine oil for Toyota Corolla. Provides maximum engine protection and fuel efficiency. Ideal for Pakistani driving conditions.',
      price: 7200,
      condition: 'new',
      stock: 25,
      images: '/products/engine-10.jpg',
      sku: 'RG-OIL-067',
      partNumber: 'MO-5W30-FS-4L',
      categoryId: engineParts.id,
      carModelId: corollaGli.id,
      featured: false,
    },
    {
      name: 'Hyundai Tucson Cabin Air Filter',
      slug: 'hyundai-tucson-cabin-air-filter',
      description: 'HEPA cabin air filter for Hyundai Tucson. Removes 99% of airborne particles including PM2.5. Essential for clean air in polluted city driving.',
      price: 2500,
      condition: 'new',
      stock: 15,
      images: '/products/engine-11.jpg',
      sku: 'RG-CFL-068',
      partNumber: 'HY-TCS-CF01',
      categoryId: engineParts.id,
      carModelId: tucson.id,
      featured: false,
    },
    {
      name: 'Suzuki Mehran Fuel Filter',
      slug: 'suzuki-mehran-fuel-filter',
      description: 'Replacement fuel filter for Suzuki Mehran. High-efficiency filtration to protect your fuel injectors and carburetor. Easy inline installation.',
      price: 600,
      condition: 'new',
      stock: 40,
      images: '/products/engine-12.jpg',
      sku: 'RG-FFL-069',
      partNumber: 'SZ-MRN-FF01',
      categoryId: engineParts.id,
      carModelId: mehran.id,
      featured: false,
    },
    {
      name: 'Honda City AC Condenser Fan Motor (Used)',
      slug: 'honda-city-ac-condenser-fan-motor-used',
      description: 'Used AC condenser fan motor for Honda City. Spins freely and operates quietly. Tested before removal from running vehicle.',
      price: 3500,
      condition: 'used',
      stock: 4,
      images: '/products/ac-11.jpg',
      sku: 'RG-ACC-070',
      partNumber: 'HN-CTY-CFM01',
      categoryId: acCooling.id,
      carModelId: city.id,
      featured: false,
    },
    {
      name: 'MG ZS Rear Bumper',
      slug: 'mg-zs-rear-bumper',
      description: 'Brand new rear bumper for MG ZS. High-quality ABS construction. Unpainted, ready for color matching. Direct bolt-on fitment.',
      price: 18000,
      condition: 'new',
      stock: 5,
      images: '/products/body-9.jpg',
      sku: 'RG-BMP-071',
      partNumber: 'MG-ZS-RB01',
      categoryId: bodyParts.id,
      carModelId: mgZs.id,
      featured: false,
    },
    {
      name: 'Honda Civic Front Shock Absorbers (Pair, Used)',
      slug: 'honda-civic-front-shock-absorbers-pair-used',
      description: 'Used front shock absorbers for Honda Civic. Still functional with no visible leaks. Affordable option for suspension repair on a budget.',
      price: 6000,
      condition: 'used',
      stock: 3,
      images: '/products/suspension-8.jpg',
      sku: 'RG-SUS-072',
      partNumber: 'HN-CVC-FSA01',
      categoryId: suspensionParts.id,
      carModelId: civic.id,
      featured: false,
    },
  ]

  const products = await Promise.all(
    productsData.map((p) => db.product.create({ data: p }))
  )
  console.log(`✅ Created ${products.length} products.`)

  // ─── 5. Create Admin User ─────────────────────────────────────────────────
  console.log('👤 Creating admin user...')
  const admin = await db.user.create({
    data: {
      email: 'admin@ravigenuine.com',
      name: 'M.Zulfiqar',
      phone: '0320-0408917',
      password: 'admin123',
      address: 'Ravi Genuine Autos, Main Market',
      city: 'Lahore',
    },
  })
  console.log(`✅ Admin user created: ${admin.email}`)

  // ─── Summary ───────────────────────────────────────────────────────────────
  console.log('\n🎉 Seed completed successfully!')
  console.log('─────────────────────────────────────')
  console.log(`  Categories:  ${categories.length}`)
  console.log(`  Car Models:  ${carModels.length}`)
  console.log(`  Products:    ${products.length}`)
  console.log(`  Admin User:  ${admin.email}`)
  console.log('─────────────────────────────────────')

  await db.$disconnect()
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e)
    process.exit(1)
  })
